#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: x86
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      configuration: Release

init:
  - cd
  - cd C:\
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" (
      echo "Downloading dependencies for Visual Studio 2015" &
      appveyor DownloadFile https://github.com/xtalopt/xtalopt-dependencies/releases/download/1.0/xtalopt-dependencies-msvc2015-32bit.zip &
      7z x xtalopt-dependencies-msvc2015-32bit.zip > nul &
      set "DEPS=C:\xtalopt-dependencies-msvc2015-32bit" &
      set "CMAKE_FLAGS=-DCMAKE_PREFIX_PATH=C:\Qt\5.11\msvc2015" &
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (
      echo "Downloading dependencies for Visual Studio 2017" &
      appveyor DownloadFile https://github.com/xtalopt/xtalopt-dependencies/releases/download/1.0/xtalopt-dependencies-msvc2017-64bit.zip &
      7z x xtalopt-dependencies-msvc2017-64bit.zip > nul &
      set "DEPS=C:\xtalopt-dependencies-msvc2017-64bit" &
      set "CMAKE_FLAGS=-DCMAKE_PREFIX_PATH=C:\Qt\5.11\msvc2017_64" &
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64)

  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DENABLE_MOLECULAR=ON
  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DEIGEN3_INCLUDE_DIR=%DEPS%\eigen_3.3.2-1

  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DLIBSSH_INCLUDE_DIRS=%DEPS%\libssh_0.7.3-1\include
  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DLIBSSH_LIBRARIES=%DEPS%\libssh_0.7.3-1\lib\ssh.lib

  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DQWT_LIBRARY=%DEPS%\qwt_6.1.3-2\lib\qwt.lib
  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DQWT_INCLUDE_DIR=%DEPS%\qwt_6.1.3-2\include

  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DBoost_INCLUDE_DIRS=%DEPS%\boost_1.6.2-1\include
  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DBoost_LIBRARY_DIRS=%DEPS%\boost_1.6.2-1\lib

  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DRDBASE=%DEPS%\rdkit_2017.09.19

  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_BUILD_TYPE=Release
  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DBUILD_INDEPENDENT_PACKAGE=ON
  - set CMAKE_FLAGS=%CMAKE_FLAGS% -DBUILD_TESTS=ON
  - set CMAKE_FLAGS=%CMAKE_FLAGS% -G "NMake Makefiles"

  - cd C:\projects\xtalopt

build_script:
  - mkdir build
  - cd build
  - echo %CMAKE_FLAGS%
  - cmake %CMAKE_FLAGS% ..
  - nmake
  - ctest --output-on-failure

after_build:
  - if %APPVEYOR_REPO_TAG% equ true (
      if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (
        echo "Tag and MSVC 2017 detected. Package will be built and md5 will be generated" &
        nmake package &
        ..\scripts\write-md5.bat
      )
    )
    else (
      echo "Tag not detected. Skipping package building and md5 generation."
    )

artifacts:
  - path: build\*-win32.exe
    name: XtalOpt
  - path: build\windows-xtalopt.md5
    name: md5sum

deploy:
  provider: GitHub
  auth_token:
    secure: AxB7eIUrpYxsEDJm8HA558RLyB6/Gt+EZ2g2ysqYB0v+rvvDkS7ArzdW99xbxTM6
  artifact: XtalOpt, md5sum
  on:
    appveyor_repo_tag: true
